### ISSUE TITLE
panic crashes bot, mask is all black

### ISSUE THREAD

**Issue by drgaberino** [bhatshravan/diepio#1]
"Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Gabe\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Gabe\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gabe\AppData\Local\Programs\Python\Python37-32\diepio-master\diepio-master\final.py", line 335, in Calcpos
    data=replace_str_index(data,Asplit2,',')
NameError: name 'replace_str_index' is not defined"

Also not sure if it's correct but attached is what my mask looks like with cv2
![image](https://user-images.githubusercontent.com/42308330/43998564-86d43c1c-9db5-11e8-82c5-c9221bac9b1b.png)

**Comment by Frankbbg** [comment]
Judging from the error you gave, the crashing is not a result of the mask, but that `replace_str_index` is not defined

The definition of the function is on line 96. You can uncomment it there and the program should work fine.
