### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Purplecreature** [bhatshravan/diepio#2]
I have gotten a syntax error when food is seen...

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Documents\Programs\Python\diepio-master\final.py", line 335, in Calcpos
    data= replace_str_index(data,Asplit2,',')
NameError: name 'replace_str_index' is not defined

**Comment by bhatshravan** [comment]
I'll check it and let you know, it's been a year since I made changes so something may have changed

**Comment by bhatshravan** [comment]
I fixed the instructions and updated the file a bit, can you pull it and run

> python final.py

Tell me if it still gives an error

**Comment by Purplecreature** [comment]
Yup, it still gives an error
![Capture](https://user-images.githubusercontent.com/51451688/59161417-38aee380-8ada-11e9-90fb-8f07a64a8c2c.PNG)

**Comment by Frankbbg** [comment]
The definition of `replace_str_index` is on line 96. You can uncomment it there and the program should work fine.
